### ISSUE TITLE
编译后运行程序 输入微信号和密码 无法登陆 错误信息为: 错误码-1, 登陆失败原因error

### ISSUE THREAD

**Issue by BoYaoEssex** [InfiniteTsukuyomi/MicroChat#4]
用vs2017编译好了，生成了MicroChat的exe, 运行之 弹出界面
输入了我的微信id和密码 （已预先测试过账号能登陆微信）
点击界面上的登陆按钮，无法登陆，在登陆按钮的下方出现一句红色的错误信息：
错误码-1, 登陆失败原因error

**Comment by BoYaoEssex** [comment]
我在代码里面单步调试跟踪到错误码为-301  
在HandleCallBackError的nCode

**Comment by binsee** [comment]
-301是重定向，再次进行请求

**Comment by leoyu10** [comment]
楼上那位编译成功的大神，项目需要设置什么吗？为什么我编译不成功呢？总是报" 在查找预编译头时遇到意外的文件结尾。是否忘记了向源中添加“#include "stdafx.h"”?"。vs2017和vs2015都遇到这个问题，这个预编译头文件没有问题啊！

**Comment by lianfei** [comment]
请教，登录时返回-301, 如果结果这个问题？

**Comment by luofucheng** [comment]
有些人是可以直接运行起来正常登录，大部分都会返回登录异常，未知错误。看来也只有作者知道是啥问题导致的
